[deck]
required_total = 30
mega_limit = 5
giga_limit = 1
dark_limit = 0

[packages]
id_whitelist = [
    "BattleNetwork6.Packs.Chips",
    "BattleNetwork6.CannonBase",
    "BattleNetwork6.RecoveryBase",
    "BattleNetwork4.AirHockeyBase",

    "BattleNetwork2.Class01.Standard.006.CrossGun",
    "BattleNetwork2.Class01.Standard.006-EX.PlusGun",
    "BattleNetwork3.Class01.Standard.011.Shotgun",
    "BattleNetwork3.Class01.Standard.012.V-Gun",
    "BattleNetwork3.Class01.Standard.013.SideGun",
    "BattleNetwork3.Class01.Standard.015.Bubbler",
    "BattleNetwork3.Class01.Standard.016.Bub-v",
    "BattleNetwork3.Class01.Standard.016-EX.BubCross",
    "BattleNetwork3.Class01.Standard.017.BubSide",
    "BattleNetwork3.Class01.Standard.017-EX.BubPlus",
    "BattleNetwork3.Class01.Standard.018.HeatShot",
    "BattleNetwork3.Class01.Standard.019.Heat-V",
    "BattleNetwork3.Class01.Standard.019-EX.HeatCross",
    "BattleNetwork3.Class01.Standard.020.HeatSide",
    "BattleNetwork3.Class01.Standard.020-EX.HeatPlus",
    "BattleNetwork3.Class01.Standard.159",
    "BattleNetwork3.Class01.Standard.160",
    "BattleNetwork3.Class01.Standard.161",
    "BattleNetwork3.Class01.Standard.185.LavaStage",

    "BattleNetwork4.Class05.Dark.001.Cannon",
    "BattleNetwork4.Class05.Dark.002.Sword",
    "BattleNetwork4.Class05.Dark.003.Bomb",
    "BattleNetwork4.Class05.Dark.004.Vulcan",
    "BattleNetwork4.Class05.Dark.005.Lance",
    "BattleNetwork4.Class05.Dark.006.Spreader",
    "BattleNetwork4.Class05.Dark.007.Stage",
    "BattleNetwork4.Class05.Dark.008.Recovery",

    "dev.GladeWoodsgrove.SwitchDrives.ArmorFire",
    "dev.GladeWoodsgrove.SwitchDrives.ArmorWood",
    "dev.GladeWoodsgrove.SwitchDrives.ArmorElec",
    "dev.GladeWoodsgrove.SwitchDrives.ArmorAqua",
    "dev.GladeWoodsgrove.SwitchDrives.ArmorCursor",
    "dev.GladeWoodsgrove.SwitchDrives.ArmorBreak",
    "dev.GladeWoodsgrove.SwitchDrives.ArmorSword",
    "dev.GladeWoodsgrove.SwitchDrives.ArmorWind",
    "dev.GladeWoodsgrove.SwitchDrives.GutsHelmet",
    "dev.GladeWoodsgrove.SwitchDrives.RapidBuster",

    "BattleNetwork6.Packs.NCPs",

    "BattleNetwork3.Program02.BreakBuster",
    "BattleNetwork3.Program04.SetGreen",
    "BattleNetwork3.Program05.SetIce",
    "BattleNetwork3.Program06.SetLava",
    "BattleNetwork3.Program07.SetSand",
    "BattleNetwork3.Program08.SetMetal",
    "BattleNetwork3.Program09.SetHoly",
    "BattleNetwork5.BusterPack",
    "dev.konstinople.augment.AddButton",
    "HubOS.Augments.Hand+",
    "dev.GladeWoodsgrove.NaviCust.SetSwordtrap",
    "dev.konstinople.augment.ArmChange",

    "BattleNetwork3.Bugs.PanelBug",
    "BattleNetwork4.Bugs.PanelBug",
    "BattleNetwork4.Bugs.ForwardMovement",
    "BattleNetwork4.Bugs.BackwardMovement",
    "BattleNetwork6.Bugs.PanelBug",
    "BattleNetwork6.Bugs.DamageHPBug",
    "BattleNetwork6.Bugs.BattleHPBug",
    "BattleNetwork6.Bugs.CustomBug",
    "BattleNetwork6.Bugs.Custom-",
    "BattleNetwork6.Bugs.BusterBug",
    "BattleNetwork6.Bugs.BusterJam",
    "BattleNetwork6.Bugs.TangoDisabled",
    "BattleNetwork6.Bugs.WarpStep",

    "BattleNetwork2.Statuses.StoneBody",
    "BattleNetwork6.Statuses.BattleHPBug",
    "BattleNetwork6.Statuses.Bubble",
    "BattleNetwork6.Statuses.EnemyAlert",
    "BattleNetwork6.Statuses.Cage",
    "BattleNetwork6.Statuses.Invincible",
    "BattleNetwork6.Statuses.Uninstall",
    "dev.GladeWoodsgrove.Statuses.Oil",

    "BattleNetwork2.TileStates.Magnet",
    "BattleNetwork3.TileStates.Sand",
    "BattleNetwork3.TileStates.Metal",
    "BattleNetwork4.TileStates.Dark",
    "BattleNetwork5.TileStates.Lava",
    "BattleNetwork5.TileStates.Sea",
    "BattleNetwork6.TileStates.Holy",
    "BattleNetwork6.TileStates.Ice",
    "BattleNetwork6.TileStates.Grass",
    "BattleNetwork6.TileStates.Poison",
    "BattleNetwork6.TileStates.Volcano",
    "BattleNetwork6.TileStates.ConveyorLeft",
    "BattleNetwork6.TileStates.ConveyorRight",
    "BattleNetwork6.TileStates.ConveyorUp",
    "BattleNetwork6.TileStates.ConveyorDown",
    "dev.GladeWoodsgrove.TileStates.Brambles",
    "dev.GladeWoodsgrove.TileStates.SwordTrap",

    "BattleNetwork6.Libraries.Conveyor".
    "BattleNetwork.Assets",
    "BattleNetwork.FallingRock",
    "BattleNetwork.WindGust",
    "BattleNetwork6.Libraries.ChipNavi",
    "BattleNetwork6.Libraries.CubesAndBoulders",
    "dev.konstinople.library.sliding_obstacle",
    "Battle.Helpers",
    "dev.konstinople.library.bomb",
    "dev.konstinople.library.panel_step",
    "dev.konstinople.library.seed_bomb",
    "BattleNetwork6.Libraries.HitDamageJudge",
    "BattleNetwork6.Libraries.PanelGrab",
    "dev.GladeWoodsgrove.library.BarriersAndAuras",
    "dev.konstinople.library.sword",
    "dev.konstinople.library.shield",
    "dev.konstinople.library.ai",
    "dev.konstinople.library.iterator",
    "dev.konstinople.library.timers",

]
id_blacklist = [
    "dev.GladeWoodsgrove.SwitchDrives.DEBUG_GAUGE",
]